services:
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: api-orders
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: api-orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
